name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"  # كل 12 ساعة يتحدث تلقائيًا
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ahmedkhaled1010  # ✨ غيّرها بالـ username بتاعك
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push new snake file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
